<?php

namespace CrypTax\Controllers;

use CrypTax\Helpers\DbHelper;
use CrypTax\Helpers\DateHelper;
use CrypTax\Helpers\VersionHelper;

use CrypTax\Models\Report;
use CrypTax\Models\ReportWrapper;

use CrypTax\PdfRender\ModelloRedditi;

use CrypTax\Render\ReportViewer;

use Exception;

class MainController
{
    public static function run() {
        $reportWrapper = new ReportWrapper(file_get_contents('/var/www/html/crypto_report/data/tx/autogenerated.csv'));
        $year = $_GET['year'] ?? DateHelper::getCurrentYear();

        //var_dump($reportWrapper->getSectionRtInfo(2013));

        echo $reportWrapper->getModelloRedditi(2021);
        echo $reportWrapper->getModelloF24(2021);
        //$report->elaborateReport(2020);
        $reportWrapper->elaborateReport($year);



        if (!isset($_GET['action'])) {
            $reportViewer = new ReportViewer($reportWrapper);
            echo $reportViewer->render();
        } elseif ($_GET['action'] === 'pdf' && isset($_GET['type'])) {
            if ($_GET['type'] === 'modello-redditi' && $reportWrapper->shouldFillModelloRedditi()) {
                $modello = new ModelloRedditi($reportWrapper->getInfoForModelloRedditi());
                echo $modello->getPdf();
            } else {
                throw new Exception('Report not available.');
            }
        } else {
            throw new Exception('Action is invalid.');
        }
    }
}
