<?php

namespace CrypTax\Controllers;

use CrypTax\Helpers\DbHelper;
use CrypTax\Helpers\DateHelper;
use CrypTax\Helpers\VersionHelper;

use CrypTax\Models\Report;

use CrypTax\PdfRender\ModelloRedditi;

use CrypTax\Render\ReportViewer;

use Exception;

class MainController
{
    public static function run() {
        $report = new Report(file_get_contents('/var/www/html/crypto_report/data/tx/autogenerated.csv'));
        $year = $_GET['year'] ?? DateHelper::getCurrentYear();
        $report->elaborateReport($year);

        $plusValenze = [];
        for ($x = $report->getFirstYear(); $x <= $report->getLastYear(); $x++) {
            $report->elaborateReport($x);
            $plusValenze[$x] = $report->getCapitalGains();
        }

        if (!isset($_GET['action'])) {
            $reportViewer = new ReportViewer($report);
            echo $reportViewer->render();
        } elseif ($_GET['action'] === 'pdf' && isset($_GET['type'])) {
            if ($_GET['type'] === 'modello-redditi' && $report->shouldFillModelloRedditi()) {
                $modello = new ModelloRedditi($report->getInfoForModelloRedditi());
                echo $modello->getPdf();
            } else {
                throw new Exception('Report not available.');
            }
        } else {
            throw new Exception('Action is invalid.');
        }
    }
}
